spring:
  datasource:
    dynamic:
      p6spy: true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          hikari:
            max-pool-size: 8 #指定连接池最大的连接数，包括使用中的和空闲的连接
          url: jdbc:mysql://localhost:3306/pricing?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 12345678
          type: com.zaxxer.hikari.HikariDataSource
          initialization-mode: always
          continue-on-error: true
          driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#swagger-ui界面开关 http://localhost:8090/swagger-ui/index.html
springfox:
  documentation:
    swagger-ui:
      enabled: true